services:
  - type: web
    name: pocket-option-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: POCKET_EMAIL
        sync: false
      - key: POCKET_PASSWORD
        sync: false
      - key: POCKET_TOKEN
        sync: false
      - key: POCKET_USER_ID
        sync: false
    healthCheckPath: /health
    autoDeploy: true